name: metabase
services:
  metabase:
    image: ${IMAGE_NAME}
    container_name: metabase

    restart: unless-stopped

    ports:
      - "${PORT}:3000"

    networks:
      - global_net

    environment:
      TZ: ${TZ}

      MB_DB_TYPE: ${MB_DB_TYPE}
      MB_DB_HOST: ${MB_DB_HOST}
      MB_DB_PORT: ${MB_DB_PORT}
      MB_DB_DBNAME: ${MB_DB_DBNAME}
      MB_DB_USER: ${MB_DB_USER}
      MB_DB_PASS: ${MB_DB_PASS}
      MB_ENCRYPTION_SECRET_KEY: ${MB_ENCRYPTION_SECRET_KEY}

      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}

    mem_limit: ${MEM_LIMIT}
    memswap_limit: ${MEM_LIMIT}

networks:
  global_net:
    external: true
